## Travis CI configuration for the ansible-cmake-module library.
##
##   <https://travis-ci.org/mdklatt/ansible-cmake-module>
##
language: python

python:
  - "2.7"

branches:
  only:
    - master
    - dev

sudo: false

addons:
  apt:  # lint.travis-ci.org doesn't recognize this yet, but it's valid
    packages:
      - cmake

install:
  - pip install -r requirements.txt -r test/requirements.txt

env:
  - ANSIBLE_LIBRARY=src

script:
  - cmake --version
  - pytest --verbose --ansible-host-pattern=localhost test/
